### ISSUE TITLE
Doesn't seem to work 3.3

### ISSUE THREAD

**Issue by teebling** [DavidIQ/ForumBanners#1]
Hello, fresh install of phpBB 3.3 running on localhost XAMMP.

I've made sure that the images/forums/ directory is there and CHMOD'ed it to 777, but I get this error when I try to upload images:

![Screen Shot 2020-06-18 at 21 10 52](https://user-images.githubusercontent.com/49092979/85067284-552f3280-b1a8-11ea-807c-47162c32db5f.png)

Also have placed some images inside the /forums/ folder but they don't show up on the settings page:

![Screen Shot 2020-06-18 at 21 12 33](https://user-images.githubusercontent.com/49092979/85067340-709a3d80-b1a8-11ea-8b01-10efa659ebaf.png)

Cheers,
Teebling

**Comment by DavidIQ** [comment]
What does the error in the server logs say?

**Comment by teebling** [comment]
No errors show up in the server's error_log or php_error_log. Also nothing shows up in the phpBB ACP error log.

Only thing I can see related is in the server's access_log, which looks like me just accessing the page in the ACP:

`::1 - - [18/Jun/2020:21:27:18 +0100] "POST /adm/index.php?i=-davidiq-ForumBanners-acp-forumbanners_module&sid=de4be2812e9671b7d5892a38d2944e74&mode=main HTTP/1.1" 200 10047`

**Comment by teebling** [comment]
Just enabled phpBB debug, this is what shows in the ACP:

`[phpBB Debug] PHP Notice: in file [ROOT]/ext/davidiq/ForumBanners/acp/forumbanners_module.php on line 132: Array to string conversion`

**Comment by DavidIQ** [comment]
That's just from `trigger_error` trying to parse the file class's error property. Try changing that line to:
```
trigger_error(join(', ', $file->error) . adm_back_link($this->u_action), E_USER_WARNING);
```
Should give you a clearer picture of what the error is.

**Comment by teebling** [comment]
That fires `GENERAL_UPLOAD_ERROR`.

Maybe something to do with me being on a local environment?

**Comment by teebling** [comment]
Hey, I've found out what the issue was - it's on my XAMMP environment - phpBB wasn't given permissions to mkdir() so I chmodded it and it's all working fine now. Sorry to bother you. Closing this issue.
